### ISSUE TITLE
Question / How-To: Hardware to be used?

### ISSUE THREAD

**Issue by Noschvie** [pvtex/esp32-rfid#4]
Hello,
thanks for this project using an ESP32.
To be sure: I ordered the "DTWonder DT-R002" and now I need the add-on board, which I have to order separately, right? Suggestion for a shop?
Thanks!

**Comment by pvtex** [comment]
You cant order the add on board right now.
But you can find all files needed to make one by yourself in this repository.

**Comment by Noschvie** [comment]
Want to order this but ends with this error:

![grafik](https://github.com/user-attachments/assets/2f150c63-c60f-4f6f-bbaa-08cdbb837ba4)

which part is needed for the level shifter?
Thanks

**Comment by pvtex** [comment]
Hi
For which base board are you trying to order?

**Comment by Noschvie** [comment]
For the "DTWonder DT-R002"

**Comment by pvtex** [comment]
For example this one on eBay 

https://www.ebay.de/itm/255283244121

**Comment by Noschvie** [comment]
Please complete the xlsx files to be used to place an order at https://jlcpcb.com
Thanks.

**Comment by pvtex** [comment]
Dont know if you can buy the level shifter there. I buy these little modules on eBay or aliexpress

**Comment by Noschvie** [comment]
@dbeinder hi David, any idea how to complete the xlsx files to place an order at https://jlcpcb.com/
Thanks.

**Comment by pvtex** [comment]
I will search if i can find the level shifter there.
If they offer it i will complete the files

**Comment by pvtex** [comment]
jlpcb does not offer that part. You have to buy it on eBay or Aliexpress and solder that part on your own.

**Comment by Noschvie** [comment]
@pvtex do you have a block diagram?

`Since we are not so sure about the polarity of U7 is correct or not.`

the files at boards/dtwonder-DT-R002 seems to be inconsistent to be used for production by jlcpcb.com.

**Comment by pvtex** [comment]
Over 20 people are using this adapter

All info (pinout, wiring plans, schematics,...) can be found on this github page

**Comment by pvtex** [comment]
This is the level shifter i use

![Screenshot_20241126_170239_eBay.jpg](https://github.com/user-attachments/assets/eda58e8c-b402-4ca2-97ae-50f407243fe4)

![Screenshot_20241126_170307_eBay.jpg](https://github.com/user-attachments/assets/54dd4ad2-b61e-4937-9103-1539f37ec86d)

**Comment by pvtex** [comment]
This is a picture of the pcb![20241126_170639.jpg](https://github.com/user-attachments/assets/536f3db0-8f71-4cc6-a4ab-3e2edc878050)

**Comment by Noschvie** [comment]
> For example this one on eBay
> https://www.ebay.de/itm/255283244121

are you sure, that this component fits to the PCB v1.6 ?
The distance of v1.6 seems to 10mm and the "level converter" component have 12,5mm
